### ISSUE TITLE
6.0.1 offset not working

### ISSUE THREAD

**Issue by Raisler84** [jayotterbein/FFXIV-Zoom-Hack#101]
I tried updating to the offset.xml information but the app still crashes for me.

**Comment by Tormentedd** [comment]
What does your setting.xml file look like? it's location is something like this C:\Users\YourPCNameGoesHere\AppData\Roaming\FFXIVZoomHack
and should look like this
![Capture](https://user-images.githubusercontent.com/13042675/146983100-c30e4762-7f95-4f1a-9493-9f34c386ee10.JPG)

**Comment by Raisler84** [comment]
thanks, that worked! I was being dumb and updating the literal "offsets.xml" file in the zip folder and not the "setting.xml" in the location you provided.

**Comment by Tormentedd** [comment]
happy it was an easy fix
