### ISSUE TITLE
Idea: I've provided a set of original icons for the project.

### ISSUE THREAD

**Issue by szalkerous** [jayotterbein/FFXIV-Zoom-Hack#108]
I noticed the project form has the generic visual studio icon.

I created a set of icons that could be used for the project in Photoshop and wanted to share them.

They are in PNG format in various sizes:
[xivzoomicons.zip](https://github.com/jayotterbein/FFXIV-Zoom-Hack/files/7966961/xivzoomicons.zip)

Feel free to use however you want, I'm releasing them here as public domain. I don't have an ICO editor installed currently, but if that's a need I could possibly find one and convert them.

**Comment by szalkerous** [comment]
I managed to compile them into ICOs:

[xivzoomicons_ICO.zip](https://github.com/jayotterbein/FFXIV-Zoom-Hack/files/7967049/xivzoomicons_ICO.zip)

**Comment by jayotterbein** [comment]
Thanks for the icons. I mentioned in another PR but I'm just without a computer atm and will get to these when I can. Looking at another 1-2 weeks

**Comment by jayotterbein** [comment]
added
