### ISSUE TITLE
First person view issue

### ISSUE THREAD

**Issue by Alucard135** [jayotterbein/FFXIV-Zoom-Hack#114]
When I zoom in to go into first person view, the camera doesn't switch to first person when the zoom distance goes below 1.5. It goes all the way to 0 and then goes to first person view. This causes the camera to go all the way into the character, gets stuck pointing downwards and then switches to first person view.

Furthermore, if "Automatically apply on load" was active, the camera doesn't go to first person view when zooming in. I also have to turn it off if I wanted to type in the FoV and max zoom values, else it will behave in a weird manner.

**Comment by Gaodust** [comment]
Same issue here

**Comment by Cyenia** [comment]
Same issue here

**Comment by Brightbrown** [comment]
Same issue here... is driving me nuts. Hope the devs can figure this one out as I have grown pretty dependant on the zoom out function.

**Comment by Tormentedd** [comment]
Sadly this is kinda a dead project, I think anyone that was really working on it has moved on or stopped playing the game so really no incentive to develop it any more. If you're comfortable looking through some code to make sure you're not downloading malware, look through some of the forks and see if anyone else is still developing it.
