### ISSUE TITLE
I must be doing something wrong

### ISSUE THREAD

**Issue by oldbuster** [jayotterbein/FFXIV-Zoom-Hack#118]
I'm terribly sorry, but I am not having much luck with ZoomHack.exe. I'm unsure where I need to extract the file and it appears no matter where I try it, it just does not work at all.
Yes I am old and retired but I am sure if someone were kind enough to join the dots for me I would be most grateful.
Kindest Regards
Obi :)

**Comment by Tormentedd** [comment]
Just making 100% sure, you're using this link https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/download/v2.1/FFXIVZoomHack.zip ? If so before you extract the .exe make sure to right click the file downloaded and unblock it and then extract to a white listed folder (Windows Defender is dumb). 
![Unblock](https://user-images.githubusercontent.com/13042675/233722421-8023c24f-7e67-49a5-ac3d-ee6693df1d64.JPG)

After that it doesn't matter where the .exe is located, just open it once the game is fully loaded and you should be good to go. Hope this helps.

**Comment by oldbuster** [comment]
Mate,Thank you for the explanation. Now I have a much better idea of what the hell Im doing. It’s generous folks like you who makes life easier an old grandfather who still loves gaming. Cheers and beers from Adelaide Australia 👍JohnSent from my iPhoneOn 22 Apr 2023, at 05:22, Tormentedd ***@***.***> wrote:﻿
Just making 100% sure, you're using this link https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/download/v2.1/FFXIVZoomHack.zip ? If so before you extract the .exe make sure to right click the file downloaded and unblock it and then extract to a white listed folder (Windows Defender is dumb).

After that it doesn't matter where the .exe is located, just open it once the game is fully loaded and you should be good to go. Hope this helps.
