### ISSUE TITLE
Sh\ut down w/o quitting the game?

### ISSUE THREAD

**Issue by Brightbrown** [jayotterbein/FFXIV-Zoom-Hack#119]
Is there a way to exit from Zoom-Hack without quitting and relaunching the game? I doubt the issue with first person view is ever going to be fixed but there are times that I need to go into 1st person view. I tried force quitting the task/process and that didn't work.

**Comment by Tormentedd** [comment]
As it's changing memory values, no you have to totally restart. Sorry about the inconvenience.

**Comment by Brightbrown** [comment]
Oh well, shame it has to be this way, as a disabled gamer the "hack" is a life saver for me.
