### ISSUE TITLE
FFXIVZoomHack just stopped working all of a sudden

### ISSUE THREAD

**Issue by falcon10474** [jayotterbein/FFXIV-Zoom-Hack#121]
This was working fine for a month and then all of a sudden it just stopped working, won't start at all on my main PC, works fine on my laptop, run as administrator does the same thing, just get the blue circle for a moment and then nothing. tried restarting my PC, uninstall/reinstall, different user, checked my registry keys are correct, tried different compatibilities, searched the web for anything that might make windows 10 just out of the blue stop running a .exe file, none of those suggestions worked. the weirdest thing ever, i was using it, working fine, then my PC rebooted out of the blue and it just never worked again. the most perplexing thing i have ever seen

**Comment by jayotterbein** [comment]
I have a suspicion the blue screen may have caused some file corruption.  You can try removing your existing settings in %AppData%\FFXIVZoomHack

**Comment by falcon10474** [comment]
holy crap that worked
thank you so much

**Comment by jayotterbein** [comment]
Awesome. It's one of those "this rarely happens" and guess I'll keep that in mind for the future that it really does sometimes.
