### ISSUE TITLE
can't zoom out? but i think i did something wrong

### ISSUE THREAD

**Issue by MandyBee93** [jayotterbein/FFXIV-Zoom-Hack#122]
hello! 

hoping someone a bit more savvy can help me out...i downloaded the file, unblocked it and it opens just fine. However when I am in game it does not seem to be properly installed because there is no 'zoom out', it just looks the same as before. Have a done something wrong or did i miss a setting some where?

Thanks so much!

**Comment by Tormentedd** [comment]
Have you changed your Zoom Max in zoom hack? Are you opening it after FFXIV is fully loaded?

**Comment by MandyBee93** [comment]
ooooh! i was opening it prior to opening the game! I also left everything default..I'll open it after next time and try changing the numbers around! thanks so so much!

**Comment by Tormentedd** [comment]
np, if it works for you let me know if not we can try some other things to get you going.
