### ISSUE TITLE
No longer working (7.0 early access)

### ISSUE THREAD

**Issue by FunnyValentine1** [jayotterbein/FFXIV-Zoom-Hack#126]
The program no longer detects FFXIV as of the launch of Dawntrail and therefore is no longer applying the FOV changes.

**Comment by wwaller** [comment]
may take a stab at this myself later if a maintainer doesnt get to it. this is the biggest QoL mod for me and the game is painful without

**Comment by PleaseFixZoomHack** [comment]
> The program no longer detects FFXIV as of the launch of Dawntrail and therefore is no longer applying the FOV changes.

There is a working fix below!

**Comment by BlackMagingway** [comment]
use old version and change offset can work

**Comment by jayotterbein** [comment]
just pointing out there are no maintainers on this project any more. I'll merge if someone else changes it, after reviewing, but it might be better to find another option

**Comment by Miral007** [comment]
> use old version and change offset can work

do you have the new offset? I tried following the directions but got lost around step 11 and then the game crashed

**Comment by manelis** [comment]
Yes the game crashes for me when I attach to it. I assume its detecting cheat engine and crashes on purpose. @jayotterbein Without bothering you much, can you explain what exactly does the approach of the current version does? Cant seem to find where the ProcessMemoryReader api comes from.

Doing a very quick check, what is failing is that it throws a exception saying is out of range. Otherwise the process is detected.

**Comment by Miral007** [comment]
> Yes the game crashes for me when I attach to it. I assume its detecting cheat engine and crashes on purpose. @jayotterbein Without bothering you much, can you explain what exactly does the approach of the current version does? Cant seem to find where the ProcessMemoryReader api comes from.
> 
> Doing a very quick check, what is failing is that it throws a exception saying is out of range. Otherwise the process is detected.



> Yes the game crashes for me when I attach to it. I assume its detecting cheat engine and crashes on purpose. @jayotterbein Without bothering you much, can you explain what exactly does the approach of the current version does? Cant seem to find where the ProcessMemoryReader api comes from.
> 
> Doing a very quick check, what is failing is that it throws a exception saying is out of range. Otherwise the process is detected.

Looks like that was added by @kingsznhone and the api source is here:
https://github.com/kingsznhone/XIV-Dev-Platform/tree/master/MemoryReader

**Comment by BlackMagingway** [comment]
If you get an error when looking for "writes to address",
change that, maybe it won't crash.
Edit → Settings → Debugger Options
→Use VEH ⇔ Use Windows

by the way, offset is 2738730

**Comment by Miral007** [comment]
> 
> by the way, offset is 2738730

I love you <3
can confirm it works with old version and this offset

**Comment by wwaller** [comment]
> > by the way, offset is 2738730
> 
> I love you <3 can confirm it works with old version and this offset

I am using a release version and just updated the offset in Settings.xml manually and am getting a memory write exception. Are you using a debug version?

Edit: Got it working. Feel free to use the "Remove DX9 Support" release and point the Offsets.xml to this branch https://github.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml (This has made my entire day, I thought I was going to have to play in zoomed-in hell for a week)

**Comment by Miral007** [comment]
Yeah the Remove DX9 version. I just grabbed the Offsets from that version's source, edited it locally, and pointed the app to the file on my desktop.

**Comment by manelis** [comment]
May make sense if we understand how from this flow the previous solution is deduced, otherwise this will keep happening.

Does that offset Fix it for both fov and zoom? Or is it different values? I only care about fov actually

**Comment by wwaller** [comment]
With this solution, the offset will need to be updated every patch, including minor patches. It seems that's how things were done until mid-2022. A change was added in mid-2022 to make this automatic, but something about that is incompatible with the 7.0 release. So yes, this will keep happening unless someone wants to take ownership of this project and fix the existing solution.

It seems like this project is unmaintained which leads me to believe there is a Dalamud plugin that solves the same problem, but Dalamud is down right now, as is the case any patch cycle.

Edit: Yes, this fixes the full functionality of FOV and zoom. The "offset" is just a memory offset that makes the premise of the hack work in the first place.

**Comment by PleaseFixZoomHack** [comment]
Sorry can someone explain in slightly simpler terms how to get this working? I don't really know what I'm doing with this stuff haha

**Comment by wwaller** [comment]
> Sorry can someone explain in slightly simpler terms how to get this working? I don't really know what I'm doing with this stuff haha

Download this older release - https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.5

Run it, change the first text field to https://github.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml and Update Offsets

Let me know if that works. This will break as soon as SE releases even a small patch to the game, if I understand correctly. Because the Syrcus Tower alliance raid has a game breaking bug that minor patch could come as soon as this week. Just an advisory.

**Comment by Timberghost** [comment]
There was a Dalamud plugin that I used but the author stopped updating it.  That is how I found this tool two years ago.

**Comment by PleaseFixZoomHack** [comment]
> > Sorry can someone explain in slightly simpler terms how to get this working? I don't really know what I'm doing with this stuff haha
> 
> Download this older release - https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.5
> 
> Run it, change the first text field to https://github.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml and Update Offsets
> 
> Let me know if that works. This will break as soon as SE releases even a small patch to the game, if I understand correctly. Because the Syrcus Tower alliance raid has a game breaking bug that minor patch could come as soon as this week. Just an advisory.

I downloaded the exe file, changed the text in the box to the address above and Updated Offset, but it just produces an error saying "problem downloading updates from [that address]". Thanks for your help with this btw!

**Comment by wwaller** [comment]
> > > Sorry can someone explain in slightly simpler terms how to get this working? I don't really know what I'm doing with this stuff haha
> > 
> > 
> > Download this older release - https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.5
> > Run it, change the first text field to https://github.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml and Update Offsets
> > Let me know if that works. This will break as soon as SE releases even a small patch to the game, if I understand correctly. Because the Syrcus Tower alliance raid has a game breaking bug that minor patch could come as soon as this week. Just an advisory.
> 
> I downloaded the exe file, changed the text in the box to the address above and Updated Offset, but it just produces an error saying "problem downloading updates from [that address]". Thanks for your help with this btw!

Could you try https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml instead?

**Comment by isybub** [comment]
I had to use a different URL, thanks for hosting it on your github :)
https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml

**Comment by PleaseFixZoomHack** [comment]
That worked!! Thank you so so much <3 You amazing people haha

**Comment by manelis** [comment]
Looked a bit at how this works and basically it looks in the process memory for the byte layout "48833D********007411488B0D********4885C97405E8********488D0D", assumes the fov and zoom come little after and applies a offset. This pattern is not found on the current game. It would be interesting to understand how @kingsznhone reached this value though. I guess the only change we need here is change that.

I tried looked a bit at the memory around the zoom value as it is changing and I dont see a remotely similar pattern around and most values keep changing. Im not used to this kind of development so I dont know how to help further. I tried at least 😅

**Comment by FunnyValentine1** [comment]
> > Sorry can someone explain in slightly simpler terms how to get this working? I don't really know what I'm doing with this stuff haha
> 
> Download this older release - https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.5
> 
> Run it, change the first text field to https://github.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml and Update Offsets
> 
> Let me know if that works. This will break as soon as SE releases even a small patch to the game, if I understand correctly. Because the Syrcus Tower alliance raid has a game breaking bug that minor patch could come as soon as this week. Just an advisory.

Thank you for this quick fix! Works like a charm!

**Comment by kingsznhone** [comment]
I'm sorry to hear that, I was AFK for about 2 years more and don't have access to ffxiv 7.0. 
I can't promise you that I will make it back to work on 7.0. 
If anyone knows how to find assembly signature like I did, he can do the fix. 

A temorary resolution: Use CE find direct offsets of 7.0 and make a new branch base on pre 2022 version. Update direct offsets in config.

**Comment by manelis** [comment]
I guess no worries as we can keep going with the manual offset for now. If you do get back to the game at some point and its not time consuming, please remember us :)

**Comment by kingsznhone** [comment]
> I guess no worries as we can keep going with the manual offset for now. If you do get back to the game at some point and its not time consuming, please remember us :) 

it's harder than most people thinking of finding signatures, require lots x86 assembly knowledges and hours carefully tracing.
 I unlock skill point and found this signature 6 yrs ago, made a private zoom assistant for myself. It's old 4.0 days bro.
Before AFK , I notice this repo and decide public to all player.

tbh, I have no confidence remember how I did this.

**Comment by wwaller** [comment]
I will take a stab at it in the coming days. Want to enjoy the game for now, but I'm sure I can figure it out.

**Comment by asmoranomar** [comment]
The CE forum has a policy against using cheats for online service games, so there's a good chance it might get removed if I post it there. Here is a cheat table that I made that works.  I use a scan method that, like the original, should persist thru minor updates.  Since I only use the zoom function, I haven't made one for FOV.  I've included pointers, but those will break on the next update.

Instructions: Remove the .txt extension and open in Cheat Engine.
[FFXIV_camera.CT.txt](https://github.com/user-attachments/files/16043500/FFXIV_camera.CT.txt)

**Comment by wwaller** [comment]
I was able to follow the instructions on the README  to find the offset myself. A hotfix is going out this week, I'll update my Offsets.xml value when that happens.

**Comment by Toxigdude91** [comment]
> > > > Sorry can someone explain in slightly simpler terms how to get this working? I don't really know what I'm doing with this stuff haha
> > > 
> > > 
> > > Download this older release - https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.5
> > > Run it, change the first text field to https://github.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml and Update Offsets
> > > Let me know if that works. This will break as soon as SE releases even a small patch to the game, if I understand correctly. Because the Syrcus Tower alliance raid has a game breaking bug that minor patch could come as soon as this week. Just an advisory.
> > 
> > 
> > I downloaded the exe file, changed the text in the box to the address above and Updated Offset, but it just produces an error saying "problem downloading updates from [that address]". Thanks for your help with this btw!
> 
> Could you try https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml instead?

Hey m8, i also did as you sugested and it worked like a charm! Untill the hotfix this saturday.. The game just got online agian and the offsets does not work anymore. Iam sorry to trouble you but i dont know how you solved the offsets last time around but it would be amazing if you could do it again!! Best regards

**Comment by asmoranomar** [comment]
New pointer is ffxiv_dx11.exe+272F730

My old CE cheat still works if you have it, but the pointers no longer show (as expected).  Here is an updated one for reference. You do not need to re-download if you don't use the pointers.

Instructions: Remove the .txt extension and open in Cheat Engine.
[FFXIV_camera.CT.txt](https://github.com/user-attachments/files/16116479/FFXIV_camera.CT.txt)

**Comment by isybub** [comment]
Converted to decimal for wwaller: 41088816

**Comment by Toxigdude91** [comment]
> New pointer is ffxiv_dx11.exe+272F730
> 
> My old CE cheat still works if you have it, but the pointers no longer show (as expected). Here is an updated one for reference. You do not need to re-download if you don't use the pointers.
> 
> [FFXIV_camera.CT.txt](https://github.com/user-attachments/files/16116479/FFXIV_camera.CT.txt)

as i really do appreciate it, the zoom has never bothered me at all. I find the vanilla zoom being adequate however i cant play with a low fov, when i bought and downloaded ffxiv during blackfriday in november 2022 (bought the complete collectors edition wich was normally 100euro but i only payed 49) and just after having made my char and logged in the very first time i downloaded this zoomhack within my first 30mins online in this game ever.  Before i buy any game i always check if there are any third party fov programs or fov changing tables availeble and if there is not i dont buy the game in the first place. I almost feel physically ill playing with a narrow fov, like you feel during a panic/angxeity attack all warm etc. 
So the only thing i want really is fov xD,  But i appreciate a quick response and thank you for the anwser.

**Comment by asmoranomar** [comment]
Give me a min

**Comment by Toxigdude91** [comment]
> Converted to decimal for wwaller: 41088816

i dont really get what i should do wtih the number. If i just click on the url wwaller left i think you mean that i should replace -
<StructureAddress>2738730</StructureAddress>
that number 2738730   to  41088816  wich you wrote. That's what i think you mean maybe iam wrong but i dont know how to change it and what you need to update the offsets is a URL link wich has the updated "offsets" just copy pasting the number in the offsets url does not solve anything. hehe sorry iam not really that good with this stuff .p

**Comment by asmoranomar** [comment]
I've added FOV to my CT.  This was a bit weird to implement, as the game doesn't allow you to adjust FOV.  I found that FOV is written when you zoom all the way in, so that's the part I am using in my scan.  Just enable the fobAOB, change to your selected value and then zoom in and the change should occur.  It's just a float value, so you'll have to figure out what FOV you want using a calculator.  Or just play around with it.

Instructions: Remove the .txt extension and open in Cheat Engine.
[FFXIV_camera.CT.txt](https://github.com/user-attachments/files/16116592/FFXIV_camera.CT.txt)

Edit: Not a lot of testing done, so feedback requested

**Comment by brpsycho** [comment]
> > Converted to decimal for wwaller: 41088816
> 
> i dont really get what i should do wtih the number. If i just click on the url wwaller left i think you mean that i should replace - 2738730 that number 2738730 to 41088816 wich you wrote. That's what i think you mean maybe iam wrong but i dont know how to change it and what you need to update the offsets is a URL link wich has the updated "offsets" just copy pasting the number in the offsets url does not solve anything. hehe sorry iam not really that good with this stuff .p

you're not far off
The number you're looking for is 272F730 - you can download wwaller's Offsets.xml file somewhere on your computer, edit it to change the address number to 272F730, save that, and instead of the url you paste the filepath of the file on your computer.

**Comment by ronniechoyy** [comment]
> > > Converted to decimal for wwaller: 41088816
> > 
> > 
> > i dont really get what i should do wtih the number. If i just click on the url wwaller left i think you mean that i should replace - 2738730 that number 2738730 to 41088816 wich you wrote. That's what i think you mean maybe iam wrong but i dont know how to change it and what you need to update the offsets is a URL link wich has the updated "offsets" just copy pasting the number in the offsets url does not solve anything. hehe sorry iam not really that good with this stuff .p
> 
> you're not far off The number you're looking for is 272F730 - you can download wwaller's Offsets.xml file somewhere on your computer, edit it to change the address number to 272F730, save that, and instead of the url you paste the filepath of the file on your computer.

Seems the address 272F730  is not work

**Comment by ronniechoyy** [comment]
> > > Converted to decimal for wwaller: 41088816
> > 
> > 
> > i dont really get what i should do wtih the number. If i just click on the url wwaller left i think you mean that i should replace - 2738730 that number 2738730 to 41088816 wich you wrote. That's what i think you mean maybe iam wrong but i dont know how to change it and what you need to update the offsets is a URL link wich has the updated "offsets" just copy pasting the number in the offsets url does not solve anything. hehe sorry iam not really that good with this stuff .p
> 
> you're not far off The number you're looking for is 272F730 - you can download wwaller's Offsets.xml file somewhere on your computer, edit it to change the address number to 272F730, save that, and instead of the url you paste the filepath of the file on your computer.

Working fine 👍

**Comment by CrmKanashii** [comment]
I have to be missing something / doing something wrong.  I changed the number in the xml file but when I post the local filepath and select update offsets it says no new update found. So when I change any of the values I get an exception error.  Any help would be appreciated as I simply cannot stand playing this game with the zoom it has.

**Comment by hiro-fa** [comment]
I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998".  I have no idea.

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Root>
  <DX11>
    <StructureAddress>272F730</StructureAddress>
    <ZoomCurrent>114</ZoomCurrent>
    <ZoomMax>11c</ZoomMax>
    <FovCurrent>120</FovCurrent>
    <FovMax>128</FovMax>
  </DX11>
  <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate>
</Root>`

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Root>
  <DX11>
    <StructureAddress>41088816</StructureAddress>
    <ZoomCurrent>114</ZoomCurrent>
    <ZoomMax>11c</ZoomMax>
    <FovCurrent>120</FovCurrent>
    <FovMax>128</FovMax>
  </DX11>
  <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate>
</Root>`

**Comment by FFSays** [comment]
> I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> 
> `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> 
> `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`

In my case it just say "No new update found" after trying both, as a xml or txt file

**Comment by brpsycho** [comment]
> > I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> 
> In my case it just say "No new update found" after trying both, as a xml or txt file

oh yeah i think you have to change the "LastUpdate" date too. do something like 2024-06-29 instead of 28.

**Comment by FFSays** [comment]
> > > I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > 
> > 
> > In my case it just say "No new update found" after trying both, as a xml or txt file
> 
> oh yeah i think you have to change the "LastUpdate" date too. do something like 2024-06-29 instead of 28.

Thanks a lot, it worked, (with 272F730 and the new date as a xml file)

**Comment by rroig7** [comment]
> > > > I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> > > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > 
> > > 
> > > In my case it just say "No new update found" after trying both, as a xml or txt file
> > 
> > 
> > oh yeah i think you have to change the "LastUpdate" date too. do something like 2024-06-29 instead of 28.
> 
> Thanks a lot, it worked, (with 272F730 and the new date)

Anyone else getting, "Problem parsing the updates from filepathhere"? I switched the address value in the offset file and I'm getting this error.

EDIT: Nvm I fixed the error, I was using wwallers Offset.xml and editing that file. I fixed it once I used the XML file that @hiro-fa made

**Comment by hiro-fa** [comment]
> > > I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > 
> > 
> > In my case it just say "No new update found" after trying both, as a xml or txt file
> 
> oh yeah i think you have to change the "LastUpdate" date too. do something like 2024-06-29 instead of 28.

Thanks, I updated LastUpdate and It worked properly!

**Comment by FFSays** [comment]
> > > > I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> > > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > 
> > > 
> > > In my case it just say "No new update found" after trying both, as a xml or txt file
> > 
> > 
> > oh yeah i think you have to change the "LastUpdate" date too. do something like 2024-06-29 instead of 28.
> 
> Thanks a lot, it worked, (with 272F730 and the new date as a txt file)


Hmm, now every time I scroll, it reset to default settings
EDIT: Rebooted the game, it doesn't reset anymore.

**Comment by CrmKanashii** [comment]
> > > I tried each script below as offsets but it cannot work and zoomhack throw "System.Exception: Could not write process memory: 998". I have no idea.
> > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>272F730</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > > `<?xml version="1.0" encoding="utf-8" standalone="yes"?> <Root> <DX11> <StructureAddress>41088816</StructureAddress> <ZoomCurrent>114</ZoomCurrent> <ZoomMax>11c</ZoomMax> <FovCurrent>120</FovCurrent> <FovMax>128</FovMax> </DX11> <LastUpdate>2024-06-28 - patch 6.1.0</LastUpdate> </Root>`
> > 
> > 
> > In my case it just say "No new update found" after trying both, as a xml or txt file
> 
> oh yeah i think you have to change the "LastUpdate" date too. do something like 2024-06-29 instead of 28.

That is such an annoyingly simple fix lol.. tyvm.

**Comment by uptheowls** [comment]
I am having great difficulty trying to figure out how to get zoomhack to work again. Everyone is saying it's so easy, but to a 57 year old like me, with no pc experience, I just cant figure it out. Any help would be very much appreciated. 

The last waller update was very easy & ty so much for that, but this is beyond me.

**Comment by uptheowls** [comment]
> I was able to follow the instructions on the README to find the offset myself. A hotfix is going out this week, I'll update my Offsets.xml value when that happens.

Are you going to be updating zoomhack after the last patch earlier today?

**Comment by Swarius** [comment]
Thank you for the updates, but I am a little confused. Is there a way to explain this with steps I don't really know how to add these fixes to get zoomhack working again after Saturdays update. I'm sorry for asking further explanation T_T

**Comment by wwaller** [comment]
I've updated https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml with the new offset

**Comment by Swarius** [comment]
> I've updated https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml with the new offset

Thank you so much!!

**Comment by Gill646** [comment]
Please I know nothing about CE and I just download the zoom hack zip. I cannot understand what is offset , and I cannot figure out how to change it. Please I really need some step by step guide. It will be very kind of anyone who can lend me a hand

**Comment by FunnyValentine1** [comment]
> Please I know nothing about CE and I just download the zoom hack zip. I cannot understand what is offset , and I cannot figure out how to change it. Please I really need some step by step guide. It will be very kind of anyone who can lend me a hand

Whenever offsets are updated, you can visit the link provided by wwaller in a previous reply and either save it as an XML file or copy the link directly. Then in the Zoom Hack tool, you can either paste the URL to the offsets or put in the path to the downloaded XML file on your computer. Once that is done, you click on "Update Offsets" and a window should appear letting you know that the tool has been updated.

Thank you wwaller for updating the offsets! I find it incredibly difficult to play XIV without the increased FOV.

**Comment by Lototele** [comment]
> I've updated https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml with the new offset

Thank you sir this worked for me as well.

**Comment by uptheowls** [comment]
> I've updated https://raw.githubusercontent.com/wwaller/FFXIV-Zoom-Hack/master/Offsets.xml with the new offset

Thank you so much, you're a gamechanger. I can finally see where I am going again :)

**Comment by asmoranomar** [comment]
I have located the pointer signature and created a merge request.
~A preliminary version can be found at https://github.com/asmoranomar/FFXIV-Zoom-Hack/releases/tag/v2.1.1~ Edit: A new version has been released on the main branch.

#128

**Comment by wwaller** [comment]
I'd recommend everyone move to this solution: https://github.com/UnknownX7/Cammy

It works with the rest of the Dalamud launcher.
