### ISSUE TITLE
App launches with unhandled exception error - Game Process cannot be found afterwards

### ISSUE THREAD

**Issue by gspark1244** [jayotterbein/FFXIV-Zoom-Hack#13]
I'm having the issue that no matter how I try to launch the compiled App (admin / non-admin, compatibility modes, etc)), I always end-up getting  an unhandled exception error upon start.

It's claiming that the value 78 is invalid for the parameter "Value" - Value should be between minimum and maximum.

Using Windows 10 64bit, .net framework 3.5+4.6(advanced) and trying to work it on the dx11 gameclient.

What am I doing wrong? Should I not use the precompiled .exe?
The Offsets provided in the xml file are the ones I get when I manually search the offsets using CE, nothing outdated in there.

Any help would be highly appreciated, I've been looking for something like this for dx11 for quite some time.

This is the exact error message:

*************\* Ausnahmetext **************
System.ArgumentOutOfRangeException: Der Wert 78 ist für Value ungültig (Value is invalid for parameter "value"). Value sollte zwischen 'Minimum' und 'Maximum' liegen  (Value should be between minimum and maximum).
Parametername: Value
   bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   bei FFXIVZoomHack.Form1.Form1_Load(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1073.0 built by: NETFXREL3STAGE.
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.

FFXIVZoomHack
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
##     CodeBase: file:///C:/Users/removingmyname:D/Desktop/FFXIV-Zoom-Hack-master/FFXIV-Zoom-Hack-master/FFXIVZoomHack/FFXIVZoomHack.exe.

System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.

System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.

System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1068.2 built by: NETFXREL3STAGE.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.

System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.

System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.

System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1064.2 built by: NETFXREL3STAGE.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.

System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.

System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.

mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.

*************\* JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by jayotterbein** [comment]
Sorry for late reply, I don't remember getting an email about this one.

I'm not sure offhand what the issue is.  There are only two up/down boxes.  The FOV uses a range of 1 to 300, and the Zoom uses 1 to 1000.  I'll try making a release without the limit on those boxes.

**Comment by jayotterbein** [comment]
I read that wrong; FOV ends at 3.00.

What I suspect happened is when writing the default setting value of `0.78` it wrote as `0,78` due to your language setting.  Does this sound right? I'm only partially aware of decimals vs commas in cultures.

To counteract this problem I'll try two things, which I have little experience in testing this:
- Modify the output and parsing to use `InvariantCulture` so that the settings always use numbers like `0.78` even if the computer's language differs.
- When reading the values in, if the FOV or Zoom are outside of the allowed range then set them to be the default.

New release here: https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/v1.1

Let me know if that worked for you.

**Comment by gspark1244** [comment]
Heya Jay,

thanks for getting back at me on this issue.
The changes you did worked like a charm, my problem's resolved completely.
Thanks a ton for this! :)

**Comment by jayotterbein** [comment]
:+1:
