### ISSUE TITLE
DX11 no longer 108?

### ISSUE THREAD

**Issue by Tormentedd** [jayotterbein/FFXIV-Zoom-Hack#20]
Was trying to get the dx11 offsets and I saw that 108 was giving me all zeros once I changed it to float. So I was messing around and tried 118 and the float was working, but not sure if that leaves everything else the same?

**Comment by jayotterbein** [comment]
It has changed once before, seen on commit 58781cb88f8914fec0ae311810e0eee78fda4e35 so it's not out of the question.  Chances are everything got increased by 0x10.

I am subbed, but I can't check for the next ~8 hours or so.

**Comment by Tormentedd** [comment]
Got them working on my fork, I'll put it here so you can look it over

 < DX11>
    < StructureAddress>1671350< /StructureAddress>
    < ZoomCurrent>118< /ZoomCurrent>
    < ZoomMax>120< /ZoomMax>
    < FovCurrent>124< /FovCurrent>
    < FovMax>128< /FovMax>
< /DX11>
had to put the space in to show

**Comment by jayotterbein** [comment]
There's a hotfix coming in tonight, so I'll wait for that.

Also to do code in a github comment put a blank line before it and indent each line 4 spaces (and additionally indent for actual code indentation).  It will output like this:

```
<DX11>
    <StructureAddress>1671350</StructureAddress>
    <ZoomCurrent>118</ZoomCurrent>
    <ZoomMax>120</ZoomMax>
    <FovCurrent>124</FovCurrent>
    <FovMax>128</FovMax>
</DX11>
```

Screenshot if it's unclear: http://imgur.com/a/PKoWQ

**Comment by Tormentedd** [comment]
This is all pretty new to me, but I really love this app so thank you for it and the info.

**Comment by jayotterbein** [comment]
Awesome, thanks for the help!
