### ISSUE TITLE
3.4

### ISSUE THREAD

**Issue by Scriva** [jayotterbein/FFXIV-Zoom-Hack#21]
When will there be an update for 3.4?

**Comment by Tormentedd** [comment]
I just put up a pull request for DX11 so those offsets should be updated soon, I was waiting to see if the hot-fix changed anything first

**Comment by jayotterbein** [comment]
For now the issue will stay open to keep track for DX9.

**Comment by Scriva** [comment]
you guys are the best :) thanks for the update!!!!
