### ISSUE TITLE
New 4.1 patch update

### ISSUE THREAD

**Issue by Alucard135** [jayotterbein/FFXIV-Zoom-Hack#31]
Hi, 

I followed your guide on how to update the offset, but the game crashes when I use the new value. One thing I noticed was that the value doesn't change at step 24 doesn't change. I've redone the process over and over, but I end up with the same offset value of 1800830.

Thanks!

**Comment by Tormentedd** [comment]
I have it working with the 1800830 on my personal fork so no idea what's happening on your end, sorry.

**Comment by Alucard135** [comment]
It worked after I restarted. Thanks!
