### ISSUE TITLE
4.1 update

### ISSUE THREAD

**Issue by nvassos** [jayotterbein/FFXIV-Zoom-Hack#33]
Hey bud, was wondering if you keep updating this, 4.1 update came up and it's not working.

**Comment by Tormentedd** [comment]
he does, sometimes it takes longer then a few days. If you need it right now use https://raw.githubusercontent.com/tormentedd/FFXIV-Zoom-Hack/master/Offsets.xml

**Comment by nvassos** [comment]
Thanks bud.

**Comment by jayotterbein** [comment]
Sorry about that, I just rarely check my email nowadays.  Thanks for the comment @Tormentedd
