### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Jana1234567** [jayotterbein/FFXIV-Zoom-Hack#44]
It simply does nothing. I even tried starting as admin. Zoom 20 or 1000, it changes nothing.

**Comment by Tormentedd** [comment]
Can I ask if you're using DX9 or 11? Because it is working for me on DX11

**Comment by Jana1234567** [comment]
Thanks for your reply. I use DX9. I just switched to 11 to test it and there it works. But my computer sucks with 11, is there any chance to get it working on 9?

**Comment by Tormentedd** [comment]
looking into it now, strangely I'm getting three offsets that all seem to be the "right" one, but they are just locking it up when I try them... I'll keep at it unless something in DX9 is different then DX11 (I have never changed DX9 before)

**Comment by Tormentedd** [comment]
ok got it working on DX9

**Comment by Jana1234567** [comment]
Thank you!!!

**Comment by Jana1234567** [comment]
Well this is weird. It worked exactly one time for me. Now I can't zoom in or out anymore. Even with defaults...

**Comment by Tormentedd** [comment]
I have it running right now. Any more info you can give me about what happened before it stopped working? I've opened and closed both the game and the program and it has worked every time

**Comment by Jana1234567** [comment]
I updated your programm, set it to 40 zoom, and at first nothing happened. I went up and down the lavender beds, trying to zoom out, and then suddenly it worked. I realised I couldn't zoom in anymore. I set it to default, nothing. I need to go to first person, then its all fine again. Thank you for looking into it :-)

**Comment by Tormentedd** [comment]
I've set it to 20 and all the way out to 1000 and am having no issues in DX9 not sure what could be going wrong on your end... sorry I couldn't help more

**Comment by Jana1234567** [comment]
No worries, I tried again, sometimes it works, it's strange somehow xD I really appreciate your work, so thank you very much!

**Comment by Tormentedd** [comment]
okay I've just tested both the main and then my own fork on another pc and for some reason the main gets stuck until you force a camera change, but the offsets on my fork (that look the same to me) aren't doing it. If you can please update from https://raw.githubusercontent.com/tormentedd/FFXIV-Zoom-Hack/master/Offsets.xml and let me know if that works without the glitch

**Comment by Tormentedd** [comment]
ok I found my mess up the FoV was 104 and needed to be 114, sorry about that and the main branch should work fine now

**Comment by Jana1234567** [comment]
Wow! Awesome! I downloaded the update and now it works absolutely well! Thank you so much :-)
