### ISSUE TITLE
Error when updating offsets; unhandled exception (Could not write process memory: 998) when adjusting zoom/FOV

### ISSUE THREAD

**Issue by heathpwns** [jayotterbein/FFXIV-Zoom-Hack#45]
I started using this about 4 or 5 months ago and it's worked perfectly.  However, since the 4.4 patch, I've been getting this issue.

When I press the Update Offsets button, I get [the following error](https://imgur.com/8ohVJCK) (only the first time, then it says there's no new update).  If I check the offsets xml afterward, it **does** in fact seem to update even though I get this error.

However, if I try to adjust my zoom or FOV after, I get [the following exception](https://imgur.com/MjERa2l):

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Exception: Could not write process memory: 998
>    at FFXIVZoomHack.Memory.Write(Single value, IntPtr handle, IntPtr address)
>    at FFXIVZoomHack.Memory.ApplyX86(Settings settings, Process process, IntPtr ptr)
>    at FFXIVZoomHack.Memory.Apply(Settings settings, Int32 pid)
>    at FFXIVZoomHack.Form1.ApplyChanges(IEnumerable`1 pids)
>    at FFXIVZoomHack.Form1.NumberChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
>    at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
>    at System.Windows.Forms.NumericUpDown.UpButton()
>    at System.Windows.Forms.UpDownBase.UpDownButtons.OnUpDown(UpDownEventArgs upevent)
>    at System.Windows.Forms.UpDownBase.UpDownButtons.BeginButtonPress(MouseEventArgs e)
>    at System.Windows.Forms.UpDownBase.UpDownButtons.OnMouseDown(MouseEventArgs e)
>    at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> FFXIVZoomHack
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/Users/heath/Downloads/FFXIVZoomHack.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3151.0 built by: NET472REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Xml.Linq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

I've tried running the app as admin, clearing the folder generated in AppData, allowing an exception for the app in the Window Firewall, and everything else I can think of.  Please assist.

**Comment by Tormentedd** [comment]
Are you running DX9 or DX11? I haven't had the chance to look over DX9 yet if you're running it.

**Comment by Tormentedd** [comment]
I just updated DX9 if that is the one you're using pls update and let me know

**Comment by heathpwns** [comment]
It's working now!  Thanks for the quick response!

**Comment by makkanocka** [comment]
hi after update 2022 25th jan it's not working seems to be the same issue, im playing with dx 11 
will there be a fix soon ?
