### ISSUE TITLE
ERROR "Access is denied"

### ISSUE THREAD

**Issue by Tjoma96** [jayotterbein/FFXIV-Zoom-Hack#46]
I've tried everything; running it as admin, changing owner permissions, disabling anti-virus etc yet I can't get the damn thing to work. It keeps throwing out the same error.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at FFXIVZoomHack.Memory.GetAddress(Byte size, Process process, IntPtr ptr, IEnumerable`1 offsets, Int32 finalOffset)
   at FFXIVZoomHack.Memory.ApplyX64(Settings settings, Process process, IntPtr ptr)
   at FFXIVZoomHack.Memory.Apply(Settings settings, Int32 pid)
   at FFXIVZoomHack.Form1.ApplyChanges(IEnumerable`1 pids)
   at FFXIVZoomHack.Form1.NumberChanged(Object sender, EventArgs e)
   at System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at System.Windows.Forms.NumericUpDown.UpButton()
   at System.Windows.Forms.UpDownBase.UpDownButtons.OnUpDown(UpDownEventArgs upevent)
   at System.Windows.Forms.UpDownBase.UpDownButtons.BeginButtonPress(MouseEventArgs e)
   at System.Windows.Forms.UpDownBase.UpDownButtons.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FFXIVZoomHack
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Tsoy/Downloads/FFXIVZoomHack%20(1).exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

**Comment by Tormentedd** [comment]
Sadly I have no idea, its working on both of my PCs both in dx11 and dx9 on win10 64bit.

**Comment by Tjoma96** [comment]
Weird.. Could it maybe have to do with the fact that I'm using a 21:9 Ultrawide monitor?

**Comment by Tormentedd** [comment]
Have it on a 21:9 UWM at 1440 so I don't think that's it.

**Comment by Tjoma96** [comment]
Goddamit then I really have no idea what might be causing it..

I'm even running it on Win 10 64-bit DX11 just like you are.

**Comment by Tjoma96** [comment]
What is your NET framework version?

**Comment by Tormentedd** [comment]
4.0.0.0
sorry tired
4.7.03056

**Comment by Tjoma96** [comment]
Sigh, I give up then. I have absolutely no clue what the issue is.

**Comment by jayotterbein** [comment]
I have some ideas, and I'll check it out this weekend

**Comment by jayotterbein** [comment]
Try release 1.2, see if that works for you:
https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/v1.2

**Comment by Tjoma96** [comment]
Tried the new release, this time I'm getting a different error.

************** Exception Text **************
System.Exception: Could not get debugging rights: Not all privileges or groups referenced are assigned to the caller ---> System.ComponentModel.Win32Exception: Not all privileges or groups referenced are assigned to the caller
   at System.Diagnostics.Process.SetPrivilege(String privilegeName, Int32 attrib)
   at System.Diagnostics.Process.EnterDebugMode()
   at FFXIVZoomHack.Memory.Apply(Settings settings, Int32 pid)
   --- End of inner exception stack trace ---
   at FFXIVZoomHack.Memory.Apply(Settings settings, Int32 pid)
   at FFXIVZoomHack.Form1.ApplyChanges(IEnumerable`1 pids)
   at FFXIVZoomHack.Form1.NumberChanged(Object sender, EventArgs e)
   at System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at System.Windows.Forms.NumericUpDown.UpButton()
   at System.Windows.Forms.UpDownBase.UpDownButtons.OnUpDown(UpDownEventArgs upevent)
   at System.Windows.Forms.UpDownBase.UpDownButtons.BeginButtonPress(MouseEventArgs e)
   at System.Windows.Forms.UpDownBase.UpDownButtons.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FFXIVZoomHack
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Tsoy/Downloads/FFXIVZoomHack.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

**Comment by jayotterbein** [comment]
Are you on a Domain?

**Comment by Tjoma96** [comment]
Nope, this is my home computer.

**Comment by jayotterbein** [comment]
I haven't had time to parse this into something smaller and more understandable.  What's happening is that somehow your account doesn't have `SeDebugPrivelege` enabled.  This is an install guide for SQL Server which explains how to check and enable it.  http://woshub.com/obtain-sedebugprivilege-debug-program-policy-enabled/

**Comment by Tjoma96** [comment]
I do in fact have debug privileges enabled on my PC, so that's not the problem.
https://gyazo.com/f95ef1c3bd443be3ac842183623b2202

EDIT: You wrote "SeDebugPrivelege" shouldn't it be SeDebugPrivilege?

**Comment by Tjoma96** [comment]
Any ideas?

**Comment by Tjoma96** [comment]
What the hell?!

I moved the program over to my other drive and all of a sudden the program started working!

**Comment by jayotterbein** [comment]
So I was going to say I didn't have ideas.. maybe there's some kind of trust issue on the default location, for example if it was a download directory then windows might block it by default? 

Either way, glad it's working.  I'll close this for now, re-open if there's something else.
