### ISSUE TITLE
I have a question about making a zoom hack.

### ISSUE THREAD

**Issue by rkelek** [jayotterbein/FFXIV-Zoom-Hack#48]
![1](https://user-images.githubusercontent.com/9375890/53584761-ae481100-3bc7-11e9-82af-aade42afcacd.JPG)
![2](https://user-images.githubusercontent.com/9375890/53584763-aee0a780-3bc7-11e9-9019-e87ebb7329df.JPG)
![3](https://user-images.githubusercontent.com/9375890/53584765-aee0a780-3bc7-11e9-81a4-0d3af8b73e46.JPG)
![4](https://user-images.githubusercontent.com/9375890/53584766-aee0a780-3bc7-11e9-9d39-b24aed8f5c8a.JPG)
![5](https://user-images.githubusercontent.com/9375890/53584768-af793e00-3bc7-11e9-9773-ecb6d32c46c1.JPG)
![6](https://user-images.githubusercontent.com/9375890/53584769-af793e00-3bc7-11e9-8f35-3665ed47a37f.JPG)
![7](https://user-images.githubusercontent.com/9375890/53584770-af793e00-3bc7-11e9-8c55-d96629ca4123.JPG)

I am a user playing on the Korean server.
I'm trying to make a zoom hack for a Korean server.
I don't understand 20-24 times in the explanation.
For more information, please refer to your photos.

**Comment by jayotterbein** [comment]
It's been a long time since I did this, and I don't have access right now to run through these steps.  Sorry if this isn't easy.


In this box 
![image](https://user-images.githubusercontent.com/5973193/53607229-75864880-3b83-11e9-9b5a-c04c8299c670.png)

try adding the values from ZoomCurrent to one of the boxes circled in blue.


The values for ZoomCurrent, ZoomMax, etc changed in version 4.4.  If the Korean server is not yet on version 4.4 you may also have to change those values.  The old values can be seen here: https://github.com/jayotterbein/FFXIV-Zoom-Hack/commit/422dac7293dcc1cd282899b9872695a3f6b0f3d9

**Comment by Tormentedd** [comment]
From what I see in the first screenshot is that you should be adding 118 to the offset. From the [r9+00000118],eax << line. If so you will need to change the ZoomCurrent, ZoomMax, FovCurrent, and the FovMax lines
    <ZoomCurrent>118</ZoomCurrent>
    <ZoomMax>120</ZoomMax>
    <FovCurrent>124</FovCurrent>
    <FovMax>12C</FovMax>
</DX11>

should be the DX11

**Comment by rkelek** [comment]
![1](https://user-images.githubusercontent.com/9375890/53608029-862ad300-3c04-11e9-82ce-374ccfa2a228.png)
![8](https://user-images.githubusercontent.com/9375890/53608056-9b076680-3c04-11e9-9bb3-cbc388dd0066.JPG)

I put in 118.
By the way, value ??...
Sorry for troubling you.

**Comment by Tormentedd** [comment]
![image](https://user-images.githubusercontent.com/13042675/53614707-cf4d3980-3ba8-11e9-878d-42e73764cba8.png)

should be how it looks

**Comment by Tormentedd** [comment]
other then this you can use the arrow beside the offset until you see one that gives you the correct number, its slow going, but if you have the right address sooner or later you should find one that will give the same value. If you want to go over this step by step I can try to explain on discord if you would like? If not I can put in photo by photo, but it will have to be some time tomorrow.

**Comment by rkelek** [comment]
I'm sorry to check late.
Thank you for your explanation in the picture.
The attached picture is to give you the information.
![n1](https://user-images.githubusercontent.com/9375890/53666706-37d40d80-3cb2-11e9-8fd8-fd5f13af70c2.JPG)
![n2](https://user-images.githubusercontent.com/9375890/53666719-402c4880-3cb2-11e9-8f23-25fe74c3b7b4.JPG)
I'm sorry to bother you.

**Comment by Tormentedd** [comment]
that looks like its it, the 19A37A0 is the part you needed to verify and looks like it is correct.

**Comment by Tormentedd** [comment]
If you need any more help its no bother and if you can please let me know how it goes.

**Comment by rkelek** [comment]
Thank you.
I think there was a problem creating the option in xml.
I re-entered the information you gave me, and it was updated properly.
Thank you again.
