### ISSUE TITLE
Change FOV directly in CE? Guide down and not very comprehensive

### ISSUE THREAD

**Issue by amenoko** [jayotterbein/FFXIV-Zoom-Hack#51]
The linked guide (https://jayotterbein.com/2016/03/13/hacking-ffxiv-zoom/) is down and even if I look at an old snapshot of it on web.archive.org, it only explains how to find the static pointer for the camera struct. It doesn't say what is done with this pointer exactly, in case I'd rather do this on my own, maybe even purely in Cheat Engine if that's possible.

I tried putting my own modified Offsets.xml into a local HTTP server and the program just reported an error. I don't know, maybe I'm doing something wrong.

Specifically, I'd like to be able to change the FOV myself without needing to rely on Offsets.xml being updated but I don't know how. I'm able to change the in-game zoom level through Cheat Engine using the guide just fine and I wonder if there is a similar method for finding the offset that holds the FOV so I can change that too? It doesn't have to be persistent, I just rather don't want to wait for the repository to get updated or worry that the author abandons it altogether. 

Sorry if that's a lot of text and thanks for any help in advance.

**Comment by amenoko** [comment]
I followed the guide and figured out the address for DX11 for this patch: 1C037A0 (https://imgur.com/a/Tv8nMqb). Changing the address in C:\Users\xyz\AppData\Roaming\FFXIVZoomHack\Settings.xml applies it locally too. I guess that solves my problem for now.

**Comment by Tormentedd** [comment]
Sorry it wasn't updated when servers came up, its a busy time of the year for me. What I used to do was change my fork and redirect the update to pull from there. Not sure why, but if you do you have to change the last line to something new or it will throw an error at you.
