### ISSUE TITLE
Found/Verified struct address (DX11) but tool not working as intended

### ISSUE THREAD

**Issue by amenoko** [jayotterbein/FFXIV-Zoom-Hack#55]
So, I'm pretty sure I found the right address for the struct. See here: https://imgur.com/a/5LHquq3

It updates between 1.5 and 20 as I zoom in and out. When I put this value (1C61F80) into StructureAddress in Settings.xml, while the tool _does_ apply a change to the game, it's definitely not the same changes as before this patch.

More specifically, the FOV seems to change as before, but as for the Zoom, when I use my mouse wheel to zoom in one step (or press the zoom in button once), it will always go into first person. When I zoom one step out, it will go to max distance. It's like there is no adjustment anymore and it's stuck in either max zoom level or first person. Changing the zoom number seems to cause randomness (like with the camera being upside down with certain values?).

Is this just on my end? I don't care much for the Zoom level personally, but it'd be nice to at least change the FOV value if nothing else (even if it's in CE; I just don't know how to look for it). I legit get motion sickness from the ridiculously small default FOV.

I fear that maybe the game code just straight up changed and the tool has to be rewritten. 

I'm also getting crashes ever since the patch (code 6e) but I can't say yet whether this is because I've been messing around with CE and this app or if it's my installation being corrupted after the patch.

**Comment by amenoko** [comment]
So I've never used Visual Studio or C# but I figured I'd try to download VS, find the bit of code that modifies the Zoom and comment it out, and compile the whole thing again. It actually works! Well, changing the FOV works (the number works differently now so the default isn't 0.78 anymore but I just lowered it until it felt right), changing the Zoom does nothing like expected.

This is what I did in Memory.cs (line 86):
```
private static void ApplyX64(Settings settings, IntPtr hProcess)
        {
            //var addr = GetAddress(8, hProcess, settings.DX11_StructureAddress, settings.DX11_ZoomMax);
            //Write(settings.DesiredZoom, hProcess, addr);
            //addr = GetAddress(8, hProcess, settings.DX11_StructureAddress, settings.DX11_ZoomCurrent);
            //Write(settings.DesiredZoom, hProcess, addr);

            var addr = GetAddress(8, hProcess, settings.DX11_StructureAddress, settings.DX11_FovCurrent);
            Write(settings.DesiredFov, hProcess, addr);
            addr = GetAddress(8, hProcess, settings.DX11_StructureAddress, settings.DX11_FovMax);
            Write(settings.DesiredFov, hProcess, addr);
        }
```

The crashes with the old build seem to be because of the build, not because of FFXIV. They don't seem to happen anymore after I built it with the above changes. Which means something must be wrong with the lines I commented out?

Sorry if I'm using this site the wrong way, I don't do any programming myself. I hope this is at least somewhat helpful. Just in case anybody else might need it in the meantime, I'm attaching the build I'm using now below (with Zoom disabled but FOV working). Settings.xml (found in %AppData%\FFXIVZoomHack\Settings.xml) needs to be modified so that the value in StructureAddress is `1C61F80`. This is for DirectX 11, I don't know about 9.

[FFXIVZoomHack.zip](https://github.com/jayotterbein/FFXIV-Zoom-Hack/files/4220539/FFXIVZoomHack.zip)

**Comment by amenoko** [comment]
It seems like the game now resets the FOV everytime a cutscene plays or you change maps. Restarting the tool, clicking "Automatically apply on load" twice, or changing the FOV number will modify it again in game. That has to be done everytime after a cutscene or changing maps apparently.

**Comment by Tormentedd** [comment]
I've been using is since 6:20ish a.m as well a few friends and none of us are having the issues you seem to be dealing with. I am using an .exe I made after the last pull to add an auto close and realign the Default Button. If you like you can try the newer .exe the offset was changed this patch so all of them needed to be 
[FFXIVZoomHack.zip](https://github.com/jayotterbein/FFXIV-Zoom-Hack/files/4222999/FFXIVZoomHack.zip)

**Comment by Tormentedd** [comment]
<DX11>
    <StructureAddress>1C61F80</StructureAddress>
    <ZoomCurrent>114</ZoomCurrent>
    <ZoomMax>11c</ZoomMax>
    <FovCurrent>120</FovCurrent>
    <FovMax>128</FovMax>
  </DX11>

if you want to just add them yourself

**Comment by amenoko** [comment]
With the offsets updated by clicking the button, everything works like before the patch. As far as my problem with the tool goes, it's completely resolved. 

Is 114 the ZoomCurrent Value? Is that the number underneath the Pointer checkbox? https://imgur.com/a/5LHquq3 Does it change every patch? Neither of the guides mentioned that value. When I went through the process as per guide, it didn't work. I would have liked to be able to update the values myself every patch instead of relying on it to get updated from outside so if possible maybe that could be added?

**Comment by Tormentedd** [comment]
I'm glade to hear that it is working for you! SE doesn't change the modifier value that often, This project is not mine so changes to the guide and such aren't anything I am comfortable making.
