### ISSUE TITLE
5.22 offset DX11

### ISSUE THREAD

**Issue by anoyetta** [jayotterbein/FFXIV-Zoom-Hack#56]
```xml
  <DX11>
    <StructureAddress>1C62F00</StructureAddress>
  </DX11>
  <LastUpdate>2019-3-17 - patch 5.22 (DX11)</LastUpdate>
```

**Comment by Tormentedd** [comment]
Sorry it took longer then normal to update, this is the first chance I could access a pc. If you can please next time make a pull request as I can okay that from my phone if I needed. Thank you
