### ISSUE TITLE
Offsets for dx9 please?

### ISSUE THREAD

**Issue by reawyy** [jayotterbein/FFXIV-Zoom-Hack#57]
Can someone update offsets for dx9?? Really appreciate it

**Comment by reawyy** [comment]
@jayotterbein @Tormentedd can you help pls

**Comment by reawyy** [comment]
Anyone can help please?

**Comment by Tormentedd** [comment]
it was my understanding that FFXIV no longer supported a DX9 version after the release of ShB, it's the reason why I never bothered to even look for the offsets. https://na.finalfantasyxiv.com/lodestone/news/detail/46f28ce6bd697e3fd08e0e70c3c7646e5f5a3385

**Comment by Tormentedd** [comment]
I switched over and put the offsets in pls let me know if its working for you

**Comment by reawyy** [comment]
@Tormentedd thanks a lot, i'll appreciate it a lot if you always update dx9 offsets when you update dx11 in future patches.many users still use dx9 even if it's not supported anymore. thank you again
