### ISSUE TITLE
new patch. update please for 5.3

### ISSUE THREAD

**Issue by ghost** [jayotterbein/FFXIV-Zoom-Hack#58]

**Comment by Drudicta** [comment]
Can also confirm. Updating the offset says that there is no update, and otherwise when attempting to change the distance I just get an "Unhandled exception." Thank you for the future fix.

**Comment by JoaoPauloBonaFissmer** [comment]
just found the new offset for patch 5.3 dx11, its "1D09BA0"

**Comment by jayotterbein** [comment]
merged in PR #59 to fix this, i can't test it myself

**Comment by Tormentedd** [comment]
works so I'll close this.
