### ISSUE TITLE
needs new offset update

### ISSUE THREAD

**Issue by AlexisBliss** [jayotterbein/FFXIV-Zoom-Hack#62]
hey think i left a comment on one of the post you guys did but yeah i recently did a full format on my pc and whne ive redownloaded this to my pc i get this https://gyazo.com/38b89334022222f0f13324e5fd43aaaf
upon following this instrustion i get this https://gyazo.com/47b202273efb22c9b11443b5b9f0078f
is there away for this to be addressed please thnak you in advance.

ps. i have no idea how all the coding works even after readuing the text on one of the pages lol so figured would come here to ask the source as there was a new update ingame on the 12/1/2021 not sure if this was the cause of the issue of not

**Comment by pr0met** [comment]
Hi Alex,

Just download this https://github.com/jayotterbein/FFXIV-Zoom-Hack/blob/a5b0918293df94aabdba0c793afabfdfc2cd725c/Offsets.xml 
And then in zoom hack, as the url, use your local path to this file such as `C:\Users\my_user\Downloads\Offsets.xml`. Then click update offsets and you're good.

**Comment by AlexisBliss** [comment]
amaxing thank you soooo much took me a little while to understand a friend of mine helped me with it all and its all working now thank you

**Comment by yellowlavender** [comment]
hello! i'm having this same issue, but i can't figure out how to change the file path. i typed it manually, but it did not work.

**Comment by AlexisBliss** [comment]
Heh sorry I've just seen this email are you still having issues? If you are
here is my discord info will be easier to help you with this my discord is
Alexis Bliss#8058
