### ISSUE TITLE
Please solve the problem

### ISSUE THREAD

**Issue by ririkpkp** [jayotterbein/FFXIV-Zoom-Hack#69]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.3
I downloaded the program from this link
and found the 5.41 offset and pasted the link

![ttrr](https://user-images.githubusercontent.com/80329589/110470816-adcfa280-811e-11eb-944f-b80d2b3d7efe.PNG)

When this phrase pops up, it won't be updated. What is the problem?

**Comment by ririkpkp** [comment]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/blob/7b201a0d6753ec0cea3ad64c42cfb09d0eac3835/Offsets.xml
The same goes for the offset here.
I am so sad...
![yrytyyy](https://user-images.githubusercontent.com/80329589/110471518-8fb67200-811f-11eb-8417-a2f576d376b4.PNG)

**Comment by Tormentedd** [comment]
The url for offsets should be https://raw.githubusercontent.com/jayotterbein/FFXIV-Zoom-Hack/master/Offsets.xml if not change them in appdata folder manually.
