### ISSUE TITLE
Cannot use ffxiv zoom hack due to update 5.5

### ISSUE THREAD

**Issue by debba12** [jayotterbein/FFXIV-Zoom-Hack#71]
The url link thats the master one is not working im getting problem parsing the updates & getting unhandled expatiations errors.

i was it was updated but i tried downloading the updated offset and its all different the url and will not work when i try it.

**Comment by ZerthVoldrin** [comment]
Same Issue.

**Comment by debba12** [comment]
does anyone have a fix or know a fix for this. Ive seen its been updated and i just keep getting the same issues no matter what i do even putting the .xml at the end what ever i do

**Comment by Tormentedd** [comment]
Try changing them locally, C:\Users\Whateveryournameis\AppData\Roaming\FFXIVZoomHack. If not try using https://raw.githubusercontent.com/tormentedd/FFXIV-Zoom-Hack/master/Offsets.xml

**Comment by debba12** [comment]
i will try when i am home in about 2 hours so i hope this can be fixed

**Comment by CaldenHartz** [comment]
I have updated the offsets via the link provided and changed the path to reflect locally.  Can confirm this has fixed the issue for me.  Originally, I was having the same issue as OP.

**Comment by Tormentedd** [comment]
thank you for letting me know it worked for you!

**Comment by debba12** [comment]
no i am getting memory offsets need updating click the update offset button which i am doing but says no update

**Comment by Tormentedd** [comment]
did you change them locally? if so you just need to run it in game and it should work

**Comment by debba12** [comment]
i will close out and reopen it and see

And yes i am no longer getting thoes 2 errors i was getting before now its just the update one

**Comment by debba12** [comment]
I am still getting Memory offsets need updating. Click the update offset button,

Then i press then it say No new updates.

I have download the offset and put it in the file locally

Unless i rename it Setting.xml was the only one I have it in there

**Comment by Tormentedd** [comment]
![Capture](https://user-images.githubusercontent.com/13042675/114652950-f3026980-9cb4-11eb-82a5-7619196690da.JPG)

is what your setting file should have in it

**Comment by Tormentedd** [comment]
Can you open Setting.xml in note pad and take a SS so I can see whats there?

**Comment by debba12** [comment]
Never mind i have fixed it. I just edtied it via note pad. Thank you for putting up with me :)

**Comment by Tormentedd** [comment]
Np, happy I could help

**Comment by debba12** [comment]
Thank you very much

**Comment by whyitdothisthough** [comment]
![dkh9hCvB71](https://user-images.githubusercontent.com/68455961/114818080-5dc8a900-9d78-11eb-95a7-b57bfaa71cb1.png)
Having the same issues but I've tried changing the offset location in the program and in the settings folder in appdata, I'm not sure what I'm doing wrong

**Comment by Tormentedd** [comment]
you're putting the wrong info in the appdata settings. Need to add the offsets back. It should look like the SS I put up in this thread 
![image](https://user-images.githubusercontent.com/13042675/114818651-22cf7100-9d8a-11eb-85d9-b33d9d827c6a.png)

**Comment by Tormentedd** [comment]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/blob/master/Offsets.xml
Copy the text from here to add back the missing parts

**Comment by whyitdothisthough** [comment]
That worked, thank you!

**Comment by Tormentedd** [comment]
np, happy zooming
