### ISSUE TITLE
Offsets.xml update problem

### ISSUE THREAD

**Issue by griffin800** [jayotterbein/FFXIV-Zoom-Hack#72]
When trying to update offsets with the app, it says "Problem parsing the updates from https://raw.githubusercontent.com/jayotterbein/FFXIV-Zoom-Hack/master/Offsets.xml"

The site says this file was updated recently for the game patch version 5.5 but I'm not sure if I am the only one having this issue

**Comment by believeinyuna** [comment]
having this issue too

**Comment by Tormentedd** [comment]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/issues/71

**Comment by griffin800** [comment]
as mentioned in #71 I was able to download the Offsets.xml file and have the program point to the local directory on my computer where it is and the program started working. this is a work around I would say but still not updating the normal way like it used to. Not complaining just informing. Love the program thanks to all who make it work

**Comment by jayotterbein** [comment]
Try updating to 1.4. Create a new issue if that didn't fix it.
