### ISSUE TITLE
error when updating offsets

### ISSUE THREAD

**Issue by believeinyuna** [jayotterbein/FFXIV-Zoom-Hack#73]
![image](https://user-images.githubusercontent.com/27219533/114686431-ad708b80-9d0a-11eb-9f85-e83c38089608.png)

**Comment by Tormentedd** [comment]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/issues/71

**Comment by believeinyuna** [comment]
the tool is working, but clicking update offsets hits this error even though it's updated and working instead of showing the "no update" message.

**Comment by Turkolton** [comment]
i copied the text of the offsets on main page - pasted it in my offsets locally, set the address to the local file address on my pc, and it worked

**Comment by jayotterbein** [comment]
Try updating to 1.4. Create a new issue if that didn't fix it.
