### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Jana1234567** [jayotterbein/FFXIV-Zoom-Hack#74]
I can't update it (problem parsing the updates) and can't zoom (could not write process memory).
Already downloaded the new version.
Any suggestions?

**Comment by hiro-fa** [comment]
Zoom hack on my computer also does not work properly and has error, "Could not write process memory: 998", even though I did not change anything.

**Comment by antcharcom** [comment]
Sorry to say this, but same issue for me.
When trying to change Field of View or Zoom Max: "Could not write process memory: 998"
And when Update Offstets, System.argumentNullException.
I can provide more details if you need them.

**Comment by Tormentedd** [comment]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/issues/71
Let me know if any of this helps, if not I can try to help if not. Sorry this took so long to reply to been sick the last few days.

**Comment by Jana1234567** [comment]
Well, yes, I changed nothing but zooming now works, don't know why.
It's just the update that does not work (parsing problem).
Thanks for your support and don't worry, I hope you get well soon.

**Comment by hiro-fa** [comment]
https://github.com/jayotterbein/FFXIV-Zoom-Hack/issues/71
It works thanks.

**Comment by antcharcom** [comment]
Hello, the fix in #71 works for me. **Thank you!!**

**Comment by literette** [comment]
I've tried to use the link provided and save them locally, still getting errors and it is not working.  Is there another solution?

**Comment by Tormentedd** [comment]
If you changed them locally and it still doesn't work I have no idea how to help you sorry

**Comment by Tormentedd** [comment]
> 
> 
> I've tried to use the link provided and save them locally, still getting errors and it is not working. Is there another solution?

Are you using dx11 or 9, if 9 its no longer being update only random thing I could think of

**Comment by jayotterbein** [comment]
Try updating to 1.4. Create a new issue if that didn't fix it.
