### ISSUE TITLE
Problem parsing the updates

### ISSUE THREAD

**Issue by macbregular** [jayotterbein/FFXIV-Zoom-Hack#75]
Hello. An update problem has occurred.
I'm a foreigner, and I'm using a translator. I'm sorry if my English is weird.

I've already read other issues but I haven't solved them.
Is it right to modify the xml file and update it by changing the URL to https://raw.githubusercontent.com/jayotterbein/FFXIV-Zoom-Hack/master/Offsets.xml?
Or is it right to enter the address of the location where my xml file is located?
Please let me know if I made a mistake.

![Cap 2021-04-22 15-58-01-223](https://user-images.githubusercontent.com/82998972/115669745-902f6300-a383-11eb-988a-00b300eb3887.png)
![Cap 2021-04-22 16-03-43-607](https://user-images.githubusercontent.com/82998972/115670387-54e16400-a384-11eb-94f1-e6c47bcebd97.png)

**Comment by Tormentedd** [comment]
you should be able to just update the dx11 offset locally, once updated the program should work. If not you can try to update from this link https://raw.githubusercontent.com/tormentedd/FFXIV-Zoom-Hack/master/Offsets.xml

**Comment by macbregular** [comment]
Sorry. Can you tell me what "update the dx11 offset locally" means?
Does that mean changing the address of OffsetUpdateLocation in the xml file?
If that's right, I tried. But I failed.

**Comment by Tormentedd** [comment]
[Settings.zip](https://github.com/jayotterbein/FFXIV-Zoom-Hack/files/6379402/Settings.zip)

These are the settings I'm using right now that are working in game you can try to replace yours in AppData\Roaming\FFXIVZoomHack with them and see if that works

**Comment by jayotterbein** [comment]
Try updating to 1.4. Create a new issue if that didn't fix it.
