### ISSUE TITLE
Finding Zoom Max

### ISSUE THREAD

**Issue by zpacedesu** [jayotterbein/FFXIV-Zoom-Hack#76]
How did you find zoom max offset?

**Comment by Tormentedd** [comment]
I honestly have no idea what you mean, sorry I can't help

**Comment by zpacedesu** [comment]
<ZoomMax>11c</ZoomMax>

This offset. How did you find it?

**Comment by Tormentedd** [comment]
I can't speak for hoe the creator of ZoomHack did, but any time the first offset has changed the others have changed by the same amount. Not sure if this is helpful, but best I can give you.
