### ISSUE TITLE
The request was aborted: Could not create a SSL/TSL secure channel

### ISSUE THREAD

**Issue by Tormentedd** [jayotterbein/FFXIV-Zoom-Hack#77]
![Capture](https://user-images.githubusercontent.com/13042675/116161598-06a0cd80-a6c2-11eb-81fe-84c92913bbda.JPG)

After trying the new release

**Comment by jayotterbein** [comment]
Try out 1.5. I can't seem to get the same errors.  https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.5

**Comment by Tormentedd** [comment]
everything seems good now, thank you.
