### ISSUE TITLE
Zoom hack

### ISSUE THREAD

**Issue by Dcakes** [jayotterbein/FFXIV-Zoom-Hack#8]
Not working for ffxiv 3.2 patch

**Comment by jayotterbein** [comment]
I can't fix this issue since I have no active account.  I used my last bit of game time to give a tutorial.

Someone else will have to submit a PR, or this is just another dead ffxiv project.

**Comment by Tormentedd** [comment]
Been trying to get it to work, but some of your tutorial is confusing me. I can get to step 12 and I do everything that you say to do, but even changing every address I only get a value of ?? so I must be messing something up(I change to decimal) . Plus is there anyway to find the address other then going through all of them?

**Comment by jayotterbein** [comment]
Sorry I wrote the guide fairly quickly and it's probably not very good if you don't already have some CE experience.  I'll see if I can get login info from a friend and get a video or image tutorial up.

**Comment by Tormentedd** [comment]
Thank you, and any help will be greatly appreciated!

**Comment by VaracolacisCrew** [comment]
Hello, I don't have much experience on CE but you can always create a free trial account using a service like 10minutemail. Or if you can provide a little more details on how to get the offset in CE I can keep the project alive I'm good at programming sadly not good with CE

**Comment by Oopdatme** [comment]
new dx11 address is 154E750, haven't bothered getting dx9 as I don't use it. thanks for getting around to the tut

**Comment by jayotterbein** [comment]
I've created a blog post with pictures to describe better how to update offsets.  Hopefully it works well enough.  https://jayotterbein.com/2016/03/13/hacking-ffxiv-zoom/

@Oopdatme thanks for the offset, i'll get that in now.
