### ISSUE TITLE
Getting a weird firewall error?

### ISSUE THREAD

**Issue by Sanaiyasu** [jayotterbein/FFXIV-Zoom-Hack#81]
![image](https://user-images.githubusercontent.com/50132165/123033158-411ea200-d3b5-11eb-85cf-dbe88cdb56d6.png)
Scans keep returning "trojan win32 zpevdo.b"? 

https://www.virustotal.com/gui/file/e0318879d6cee0842bdce75c051b452c30c6fb0c9873e6d51070bca5d6a6f1f2/detection

**Comment by Clueless-AI** [comment]
Same issue here, I was using the tool for a very long time and now apparently Windows defender is blocking it because there's some sort of Trojan.

**Comment by seathasky** [comment]
DONT DOWNLOAD THIS!

**Comment by seathasky** [comment]
![9r43Itv](https://user-images.githubusercontent.com/17598024/124584280-0c353500-de22-11eb-924f-6bfbf458a58d.png)

**Comment by Tormentedd** [comment]
It's a false positive, look through the code and compile it yourself if you think it isn't... or don't.

**Comment by seathasky** [comment]
> It's a false positive, look through the code and compile it yourself if you think it isn't... or don't.

![111](https://user-images.githubusercontent.com/17598024/124585019-e52b3300-de22-11eb-9ff1-aafb3dee8764.png)
Yea, you're right.. Seems to work just fine.
