### ISSUE TITLE
This tool broken?

### ISSUE THREAD

**Issue by Moshstep** [jayotterbein/FFXIV-Zoom-Hack#85]
Is there any offsets available for 5.55 or some sort of download? I've tried updating offsets manually but the guide is confusing towards the end with the green ones thing. Any help would be appreciated

**Comment by Tormentedd** [comment]
Tool is working fine for me, though not sure why you need the 5.55 offsets? Current patch is 5.58? If you're trying to change them manually/locally you need to edit the offset in the settings file C:\Users\(What ever you named your PC)\AppData\Roaming\FFXIVZoomHack once you open Settings with any text editor you should see this

![Setting pic](https://user-images.githubusercontent.com/13042675/128612683-cf1fdeb3-58d7-4dd4-b7fd-4fd92595f3c7.JPG)

If you get to this point and everything looks the same (be careful with the offset this time around it looks almost the same as last time) and it still doesn't work let me know and I'll try to help you from there.

**Comment by Tormentedd** [comment]
going to guess you got it working?

**Comment by Moshstep** [comment]
Sorry about the late response, yeah I didn't realize it was 5.58 now guess I didn't consider the smaller updates added to the patch version, but yea I got it working now. I do have another question as to why the newer download of zoomhack comes back as a Uwamson.A!ml trojan, I'm assuming it's a false positive but it's never happened on any other download version as far as I know, what's new about the newer download that makes it detected by wDef as a trojan?

**Comment by jayotterbein** [comment]
The newer version downloads the XML from github first directly, instead of relying on the XDocument, and set the TLS to 1.2.

I'm not sure why it would be picked up differently.

The changes are:
https://github.com/jayotterbein/FFXIV-Zoom-Hack/commit/ada719cc99d2a05cd6a06dd7d2d9b0f6d323d7b3
https://github.com/jayotterbein/FFXIV-Zoom-Hack/commit/d2e997a65a90f0e5a7dc3fe521794f9090f04910
