### ISSUE TITLE
offset update 

### ISSUE THREAD

**Issue by AlexisBliss** [jayotterbein/FFXIV-Zoom-Hack#86]
hey, there was a new patch update in game today was wonderign if you was aware of this and are looking into updating the offsets for this software?
also thats update windows defender was filign this as a trojan and idea why that could be happening as this is the first time its happened.
kind regards

**Comment by Haduis** [comment]
https://www.virustotal.com/gui/file/e0318879d6cee0842bdce75c051b452c30c6fb0c9873e6d51070bca5d6a6f1f2/detection seems like a false positive. Also @jayotterbein can you upload a video somewhere of you re-scanning offsets? I tried following your instructions but I think i got something wrong on 22 onward.

**Comment by Haduis** [comment]
oh wow i did it, new address is:    1DAEF70

**Comment by AlexisBliss** [comment]
wait how do i change it

**Comment by Haduis** [comment]
C:\Users\Name\AppData\Roaming\FFXIVZoomHack\Settings.xml and change the "StructureAddress". Use Notepad to edit it.

**Comment by AlexisBliss** [comment]
omg thank you soo much 
it worked your amazing

**Comment by Haduis** [comment]
haha nice I did it!
