### ISSUE TITLE
New address is 1DAEF70

### ISSUE THREAD

**Issue by Haduis** [jayotterbein/FFXIV-Zoom-Hack#87]
1DAEF70

**Comment by AlexisBliss** [comment]
how would i apply this new address please

**Comment by Haduis** [comment]
- Close the program
- Open "C:\Users\Name\AppData\Roaming\FFXIVZoomHack\Settings.xml" with Notepad
- Change the "StructureAddress" portion to 1DAEF70
- Save Settings.xml
- Open the program again and try it out

If I was wrong about the offset big sorry but it's working for me for sure.

**Comment by Haduis** [comment]
Looks like the offset worked for AlexisBliss too so it is correct.

**Comment by jayotterbein** [comment]
I updated the xml to change the offset
