### ISSUE TITLE
offset

### ISSUE THREAD

**Issue by jojo0225** [jayotterbein/FFXIV-Zoom-Hack#88]
I don't know what's wrong.
![スクリーンショット (35)](https://user-images.githubusercontent.com/89465027/130627675-42f8bb3c-18b0-4ee6-9c6a-ebf8968b9138.png)
teach me please!

**Comment by Haduis** [comment]
StructureAddress is what you should change, save that and restart the EXE. Maybe my offset is wrong?

**Comment by AlexisBliss** [comment]
offset worked perfectly thank you again @Haduis

**Comment by jojo0225** [comment]
Can you tell me the content of the text?
I'm Japanese, so I'm not good at English.sorry.わ

**Comment by Haduis** [comment]
"StructureAddress" should have the text 1DAEF70. It looks like you have already done this correctly, did you close the application and start it again? It should be the fourth line.

![image](https://user-images.githubusercontent.com/49592714/130630762-ac95ee50-8049-40e0-9ed8-41b4c7059101.png)

**Comment by Clueless-AI** [comment]
Thank you Haduis for the precious help, I just wanted to ask you if there's a way to get the Structure Address without using CE ?

**Comment by jayotterbein** [comment]
I've updated the XML with the new offset.  And there's no good way to get the address without CE, you'll need to reverse it somehow and it's just the simplest tool for these smaller finds
