### ISSUE TITLE
Unhandlex exception - could not process memory: 299

### ISSUE THREAD

**Issue by BWalrus** [jayotterbein/FFXIV-Zoom-Hack#90]
Overnight it suddenly stopped working and I'm not sure why. I keep getting this error: https://imgur.com/a/pExvF2K

I tried redownloading ZoomHack entirely and deleted the folder in AppData as well, and got this error after trying to update offsets: https://imgur.com/a/IUhJOHF

The offset in my settings file is 1DAEF70. A friend of mine's ZoomHack still works and their offset is 1DB7F70. I tried using their ZoomHack file and settings file and still for some reason it won't work. I've tried running it as administrator and still no dice.

**Comment by harveylx** [comment]
Also getting the same error now

**Comment by JadeyNL** [comment]
same here

Edit: disabling ACT workt for me, but still getting the error for some reason

**Comment by Douglas890116** [comment]
Same error, anybody know how to solve it ?
