### ISSUE TITLE
Windows Defender recognising exe as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by IsaacKhor** [jayotterbein/FFXIV-Zoom-Hack#91]
Not sure if this is affecting other users, but Windows Defender detects it as the above in title
![image](https://user-images.githubusercontent.com/30614624/134814249-5a0fb02f-c36c-455d-9dbc-02e1e383d21d.png)

VirusTotal results here: https://www.virustotal.com/gui/file/e0318879d6cee0842bdce75c051b452c30c6fb0c9873e6d51070bca5d6a6f1f2/detection

Not accusing author of anything, but I'm just looking through the source. Process injections always trigger something with AV, so probably nothing here.

**Comment by iv230** [comment]
Got the same thing. First is was a Chrome trigger, when a Windows one
However, tool working perfectly

**Comment by jayotterbein** [comment]
Related to #98 

I don't plan to fight windows defender.
