### ISSUE TITLE
Windows 11 Compatibility Issues

### ISSUE THREAD

**Issue by abcgxp** [jayotterbein/FFXIV-Zoom-Hack#92]
### Subject of the issue

The FFXIV Zoom Hack utility is not currently compatible with Windows 11

### Your environment

Edition	Windows 11 Pro
Version	21H2
Installed on	‎9/‎30/‎2021
OS build	22000.258
Experience	Windows Feature Experience Pack 1000.22000.258.0

### Steps to reproduce

Open the FFXIV Zoom Hack application while running Windows 11

### Behavior 

When opening the application while running Windows 11 you will be met with this. 

![Screenshot 2021-10-26 185801](https://user-images.githubusercontent.com/38545191/138972766-3da1c1ad-8eb3-49e9-bc0c-35873533161c.png)

**Comment by Cyenia** [comment]
I have no problems under Windows 11

Edition	Windows 11 Pro
Version	21H2
Installed on	‎1/2/‎2022
OS build	22000.675
Experience Windows Feature Experience Pack 1000.22000.675.0

Maybe you should update it?
