### ISSUE TITLE
FFXIV-Zoom-Hack

### ISSUE THREAD

**Issue by Whateveraya** [jayotterbein/FFXIV-Zoom-Hack#93]
Hello, i used it with my old Pc the whole time without errors but with my new computer that uses DX 12 it says you cannot perform the Programm with your Computer please ask the Administrator of the Software... and then it automaticly deletes the Programm...
Can you maybe help me with that issue please?

Greetings,
Sandra

**Comment by cyristm** [comment]
DX12 is backwards compatible. 

Your Anti-virus might be flagging FFXIV Zoom Hack as a virus. It is a false positive, so you'll need to add an exception so your AV will allow the program to open

**Comment by jayotterbein** [comment]
Sounds like windows defender if it's deleting the program. Probably related to #98
