### ISSUE TITLE
Window defender recognizing .exe as Uwamson.A!ml

### ISSUE THREAD

**Issue by milkcoco12** [jayotterbein/FFXIV-Zoom-Hack#98]
Window defender recognizing .exe as a file infected from virus called uwamson.a!ml. It alerts me even i download the new .exe after deleting the previous infected file with antivirus program/window defender.

**Comment by jayotterbein** [comment]
I don't plan to try and fight windows defender. We're opening a process and changing memory, that's a behavior defender does not like. You'll have to add an exemption if you wish to use this, or try another app.

The source is open if you want to compile yourself if you feel unsafe with the executable.
